/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    WfButton: typeof import('@weifengwa/components/src/button')['WfButton']
    WfDialog: typeof import('@weifengwa/components/src/dialog')['WfDialog']
    WfIcon: typeof import('@weifengwa/components/src/icon')['WfIcon']
    WfScroll: typeof import('@weifengwa/components/src/scroll')['WfScroll']
    WfSpace: typeof import('@weifengwa/components/src/space')['WfSpace']
    WfSwitch: typeof import('@weifengwa/components/src/switch')['WfSwitch']
  }
}
